{"80539b13cf76e3c2571a0ba6d7f45fe8":{"statistic":{"failed":0,"broken":1,"skipped":0,"passed":0,"unknown":0,"total":1},"items":[{"uid":"1759bc3097a039d2","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='selenoid.autotests.cloud', port=443): Max retries exceeded with url: /wd/hub/session (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1028)')))","time":{"start":1756413172390,"stop":1756413172390,"duration":0}}]}}